[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tipjar_receipts = "7YaPMHgDfdBxc3jBXKUDGk87yZ3VjAaA57FoiRy5VG7q"
tipjar_mxe = "AuoVDGoVfQaRdKGGkrgQyfpcGrJt9P6C8AqVSkNoqo5i"

[programs.devnet]
tipjar_receipts = "7YaPMHgDfdBxc3jBXKUDGk87yZ3VjAaA57FoiRy5VG7q"
tipjar_mxe = "AuoVDGoVfQaRdKGGkrgQyfpcGrJt9P6C8AqVSkNoqo5i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
