[localnet]
# number of nodes in the single cluster of the localnet
nodes = 2
# number of seconds to wait for the localnet to come online
localnet_timeout_secs = 60
# MPC backends this MXE supports (default: ["Cerberus"])
backends = ["Cerberus"]

[toolchain]
arcium_version = "0.3.0"

[programs.localnet]
tipjar_mxe = "AuoVDGoVfQaRdKGGkrgQyfpcGrJt9P6C8AqVSkNoqo5i"

[programs.devnet]
tipjar_mxe = "AuoVDGoVfQaRdKGGkrgQyfpcGrJt9P6C8AqVSkNoqo5i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "arcium test"

[features]
resolution = true
skip-lint = false
