# ./Cargo.toml  (root)
[workspace]
members = [
    "programs/tipjar-receipts",
    "programs/tipjar-mxe",  # NEW: Add MXE program to workspace
    "encrypted-ixs"
]
resolver = "2"

[profile.release]

overflow-checks = true


