[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
tipjar_mxe = "AuoVDGoVfQaRdKGGkrgQyfpcGrJt9P6C8AqVSkNoqo5i"

[programs.devnet]
tipjar_mxe = "AuoVDGoVfQaRdKGGkrgQyfpcGrJt9P6C8AqVSkNoqo5i"

[toolchain]
arcium_version = "0.3.0"

[localnet]
nodes = 2
localnet_timeout_secs = 60
backends = ["Cerberus"]
