[package]
name = "tipjar_receipts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }

[features]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]

